export const ADDRESS_CHANGE = 'ADDRESS_CHANGE'
export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL'
